#!/usr/bin/env python3
"""Generate vectors.json. Independent of the Rust and C codecs on purpose (own CRC, own framing)."""
import json, struct, pathlib

def crc16(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc

assert crc16(b"123456789") == 0x29B1

def frame(ver, typ, flags, seq, payload=b"", len_override=None):
    n = len(payload) if len_override is None else len_override
    body = bytes([ver, typ, flags, seq]) + struct.pack("<H", n) + payload
    return body + struct.pack("<H", crc16(body))

ACK, RESP = 1, 2
valid, invalid = [], []

def v(name, typ, flags, seq, payload=b""):
    f = frame(1, typ, flags, seq, payload)
    valid.append(dict(name=name, hex=f.hex(), ver=1, type=typ, flags=flags, seq=seq, payload=payload.hex()))

uuid = bytes(range(0xA0, 0xB0))
v("hello", 0x01, 0, 0, bytes([1, 0]))
v("hello_ack", 0x01, RESP, 0, bytes([1, 0]) + struct.pack("<I", 0b111) + bytes([0, 1, 0]) + uuid + bytes([6]) + b"kvm-it")
v("key_down_a_ack", 0x10, ACK, 1, bytes([0x04]))
v("key_up_a_ack", 0x11, ACK, 2, bytes([0x04]))
v("key_tap_enter", 0x12, ACK, 3, bytes([0x28]))
v("key_down_left_shift", 0x10, ACK, 4, bytes([0xE1]))
v("key_down_ack_response", 0x10, RESP, 1)
v("mouse_move_neg", 0x20, 0, 250, struct.pack("<hh", -5, 300))
v("mouse_move_extremes", 0x20, 0, 0, struct.pack("<hh", -32768, 32767))
v("mouse_button_down_left", 0x21, ACK, 5, bytes([0x01]))
v("mouse_button_up_all", 0x22, ACK, 6, bytes([0x07]))
v("scroll", 0x23, ACK, 7, struct.pack("<bb", -1, 3))
v("release_all", 0x30, ACK, 255)
v("ping_echo_payload", 0x40, 0, 9, b"\x01\x02\x03\x04\x05\x06\x07\x08")
v("ping_empty", 0x40, 0, 10)
v("status_response", 0x50, RESP, 11, bytes([1, 2, 1]) + struct.pack("<II", 7, 3))
v("set_name", 0x60, ACK, 12, bytes([4]) + b"desk")
v("set_boot_drive_on", 0x61, ACK, 15, bytes([1]))
v("set_boot_drive_off", 0x61, ACK, 16, bytes([0]))
v("status_response_with_boot_drive", 0x50, RESP, 17, bytes([1, 2, 1]) + struct.pack("<II", 7, 3) + bytes([1]))
v("error_unsupported", 0x7F, RESP, 13, bytes([1, 0x99]))
v("max_payload", 0x40, 0, 14, bytes(i & 0xFF for i in range(240)))

def bad(name, raw, error):
    invalid.append(dict(name=name, hex=raw.hex(), error=error))

good = frame(1, 0x10, ACK, 1, bytes([4]))
bad("empty", b"", "Truncated")
bad("seven_bytes", good[:7], "Truncated")
bad("missing_crc_byte", good[:-1], "LengthMismatch")
bad("extra_trailing_byte", good + b"\x00", "LengthMismatch")
bad("len_field_too_big", frame(1, 0x10, ACK, 1, bytes([4]), len_override=5), "LengthMismatch")
bad("payload_over_max", frame(1, 0x40, 0, 1, bytes(241)), "PayloadTooLong")
flipped = bytearray(good); flipped[6] ^= 0x01
bad("flipped_payload_bit", bytes(flipped), "BadCrc")
crcflip = bytearray(good); crcflip[-1] ^= 0xFF
bad("flipped_crc", bytes(crcflip), "BadCrc")
bad("unknown_major", frame(2, 0x10, ACK, 1, bytes([4])), "BadVersion")
bad("version_zero", frame(0, 0x10, ACK, 1, bytes([4])), "BadVersion")
bad("reserved_flag_bit2", frame(1, 0x10, 0x04, 1, bytes([4])), "BadFlags")
bad("reserved_flag_bit7", frame(1, 0x10, 0x80, 1, bytes([4])), "BadFlags")
bad("unknown_type", frame(1, 0x55, 0, 1), "UnknownType")

pathlib.Path(__file__).with_name("vectors.json").write_text(json.dumps(
    dict(spec="protocol/SPEC.md", crc16_check=dict(ascii="123456789", crc=0x29B1, max_payload=240),
         valid=valid, invalid=invalid), indent=2) + "\n")
print(len(valid), "valid,", len(invalid), "invalid")

# Line-oriented mirror for the C tests (no JSON parser in firmware tests). '-' = empty payload.
lines = ["# generated by gen_vectors.py — do not edit",
         "# V name frame_hex type flags seq payload_hex", "# I name frame_hex error"]
for x in valid:
    lines.append(f"V {x['name']} {x['hex']} {x['type']} {x['flags']} {x['seq']} {x['payload'] or '-'}")
for x in invalid:
    lines.append(f"I {x['name']} {x['hex'] or '-'} {x['error']}")
pathlib.Path(__file__).with_name("vectors.txt").write_text("\n".join(lines) + "\n")
