#!/usr/bin/env bash
# Get a machine ready to work on kvm-it, and say plainly what is missing. Safe to re-run; it changes nothing except
# (unless --check) building the Rust build container image the first time.
#   scripts/bootstrap.sh [--check] [--firmware]
#     --check     report only: build nothing
#     --firmware  also build the ESP-IDF firmware image (large; only needed to build or flash firmware)
# Exit status 1 if something required is missing.
set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHECK=0; FW=0
for a in "$@"; do case "$a" in --check) CHECK=1;; --firmware) FW=1;; *) echo "usage: $0 [--check] [--firmware]" >&2; exit 2;; esac; done
bad=0
ok()   { printf '  ok    %s\n' "$*"; }
warn() { printf '  WARN  %s\n' "$*"; }
miss() { printf '  MISS  %s\n' "$*"; bad=1; }
have() { command -v "$1" >/dev/null 2>&1; }
OS="$(uname -s)"
echo "kvm-it bootstrap: $OS $(uname -m), repo $ROOT"

echo "-- tools"
for t in git python3; do have "$t" && ok "$t" || miss "$t is not installed"; done
if have gh; then
    if gh auth status >/dev/null 2>&1; then ok "gh, logged in"; else miss "gh is installed but not logged in: run 'gh auth login' (issues, PRs and releases need it)"; fi
else miss "gh (GitHub CLI) is not installed"; fi
if [ "$OS" = Linux ]; then
    RT="${CONTAINER_RUNTIME:-podman}"
    if have "$RT"; then ok "$RT (the host has no Rust or ESP-IDF toolchain: scripts/rs.sh and fw.sh run in containers)"; else miss "$RT is not installed: scripts/rs.sh test|clippy|build and fw.sh need it"; fi
else
    have cargo && ok "cargo (native build; macOS preview: see scripts/build-dmg.sh)" || warn "cargo not installed: install via rustup (1.99.0 matches the containers)"
fi
have ffmpeg && ok "ffmpeg (needed to RECORD; also used by the recorder's end-to-end tests)" || warn "ffmpeg not found: the Record button will say so, and the recorder's e2e tests skip"
have codex && ok "codex CLI (astra adversarial review, STD-001)" || warn "codex CLI not found: adversarial review (STD-001) cannot be run from here"

echo "-- disk"
free_gb="$(df -Pk "$ROOT" | awk 'NR==2{printf "%d", $4/1048576}')"
if [ "${free_gb:-0}" -ge 20 ]; then ok "${free_gb} GB free"; else
    warn "only ${free_gb} GB free here: container builds fail with 'no space left' below ~10 GB. The build cache is disposable: rm -rf $ROOT/desktop/target/debug (regenerated by scripts/rs.sh test); 'podman image prune -f' drops unused images"; fi
if [ -d "$ROOT/desktop/target" ]; then ok "build cache $(du -sh "$ROOT/desktop/target" 2>/dev/null | cut -f1) in desktop/target (disposable)"; fi

echo "-- repo"
if git -C "$ROOT" fetch -q 2>/dev/null; then ok "fetched origin"; else warn "could not fetch origin (offline?)"; fi
echo "        branch: $(git -C "$ROOT" branch --show-current) ($(git -C "$ROOT" rev-parse --short HEAD))   version: $(tr -d '[:space:]' < "$ROOT/VERSION")"
wt="$(git -C "$ROOT" worktree list | wc -l | tr -d ' ')"
[ "$wt" -gt 1 ] && warn "$wt worktrees exist ('git worktree list'); remove stale ones with 'git worktree remove'"

if [ "$OS" = Linux ] && have "${CONTAINER_RUNTIME:-podman}"; then
    echo "-- build containers"
    RT="${CONTAINER_RUNTIME:-podman}"
    IMG="$(sed -n 's/^IMAGE="${RS_IMAGE:-\(.*\)}"/\1/p' "$ROOT/scripts/rs.sh")"
    if "$RT" image exists "$IMG" 2>/dev/null; then ok "$IMG present"
    elif [ "$CHECK" = 1 ]; then warn "$IMG missing (run without --check to build it, a few minutes)"
    else
        echo "  ...   building $IMG (first time on this machine)"
        if "$ROOT/scripts/rs.sh" image >/dev/null 2>&1; then ok "$IMG built"; else miss "building $IMG failed (disk space? run: scripts/rs.sh image)"; fi
    fi
    if [ "$FW" = 1 ]; then
        if [ "$CHECK" = 1 ]; then warn "--firmware with --check builds nothing"; else "$ROOT/scripts/fw.sh" image >/dev/null 2>&1 && ok "firmware image built" || warn "firmware image build failed (scripts/fw.sh image)"; fi
    fi
fi

if [ "$OS" = Linux ]; then
    echo "-- the adapter board (only matters when flashing or doing hardware passes)"
    if [ -e /dev/ttyACM0 ]; then
        if [ -r /dev/ttyACM0 ] && [ -w /dev/ttyACM0 ]; then ok "/dev/ttyACM0 present and accessible"
        else warn "/dev/ttyACM0 present but not accessible: join 'dialout' (re-login) or add a udev uaccess rule; a setfacl on it is lost on replug"; fi
        warn "NEVER flash with the board's USB port plugged into this machine: the self-test types into it"
    else ok "no board attached (fine; unit tests and the container build need none)"; fi
    id -nG | tr ' ' '\n' | grep -qx dialout && ok "user is in 'dialout'" || warn "user is not in 'dialout' (needed for the COM port)"
    echo "-- Bluetooth"
    if have bluetoothctl && bluetoothctl show >/dev/null 2>&1; then ok "a BlueZ adapter is present"; else warn "no BlueZ adapter seen: pairing and hardware passes need one (a USB dongle works)"; fi
fi

echo
if [ "$bad" = 0 ]; then echo "ready. Next: scripts/rs.sh test && scripts/rs.sh clippy"; else echo "NOT ready: fix the MISS lines above, then re-run scripts/bootstrap.sh"; fi
exit "$bad"
