#!/usr/bin/env python3
"""THIRD_PARTY_LICENSES.html: the generated licence listing of every Rust crate in the shipped desktop app.

  scripts/licenses.py --stamp     after scripts/rs.sh licenses: record the inputs' hash in the file
  scripts/licenses.py --check     CI: fail if the listing is stale (see below) or truncated

The file is generated by cargo-about (`scripts/rs.sh licenses`); its first line records a hash of the inputs (the lockfile,
every manifest, the vendored crates, the cargo-about config, template and version), so CI can spot a stale listing without
installing cargo-about. The check also makes sure the listing is not truncated: it must name most of the locked crates.
"""
import hashlib, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD_PARTY_LICENSES.html"
STAMP = re.compile(r"<!-- inputs-sha256: ([0-9a-f]{64}) -->\n")
MUST_NAME = ("btleplug", "eframe", "egui", "serialport", "espflash", "tokio")   # direct dependencies of the shipped app

def inputs():
    d = ROOT / "desktop"
    files = [d / "Cargo.lock", d / "Cargo.toml", d / "about.toml", d / "about.hbs", ROOT / "scripts" / "rs.sh"]
    files += sorted(d.glob("crates/*/Cargo.toml")) + sorted(p for p in (d / "vendor").rglob("*") if p.is_file())
    return [p.relative_to(ROOT).as_posix() for p in files]

def inputs_hash():
    h = hashlib.sha256()
    for p in inputs():
        data = (ROOT / p).read_bytes().replace(b"\r\n", b"\n")
        if p == "scripts/rs.sh":   # only the pinned cargo-about version matters there
            data = b"".join(re.findall(rb"^CARGO_ABOUT_VERSION=.*$", data, re.M))
        h.update(p.encode() + b"\0" + data + b"\0")
    return h.hexdigest()

def check_content(text):
    """A truncated or emptied listing fails even with the right stamp."""
    locked = set(re.findall(r'^name = "([^"]+)"', (ROOT / "desktop" / "Cargo.lock").read_text(), re.M))
    locked -= {p.parent.name for p in (ROOT / "desktop").glob("crates/*/Cargo.toml")}
    named = set(re.findall(r'<li><a href="[^"]*">([^ <]+) [^<]+</a></li>', text))
    missing = [n for n in MUST_NAME if n not in named]
    if missing or len(named) < len(locked) // 2 or "<pre>" not in text:
        sys.exit(f"FAIL: {OUT.name} looks truncated: names {len(named)} of {len(locked)} locked crates"
                 + (f", missing {', '.join(missing)}" if missing else "") + ": run scripts/rs.sh licenses")
    return len(named), len(locked)

def main():
    flag = sys.argv[1] if len(sys.argv) == 2 else ""
    if flag not in ("--stamp", "--check"):
        print(__doc__)
        sys.exit(2)
    if not OUT.exists():
        sys.exit(f"FAIL: {OUT.name} is missing: run scripts/rs.sh licenses")
    text = OUT.read_text(encoding="utf-8")
    m = STAMP.match(text)
    if flag == "--stamp":
        OUT.write_text(f"<!-- inputs-sha256: {inputs_hash()} -->\n" + (text[m.end():] if m else text), encoding="utf-8")
        named, locked = check_content(text)
        print(f"stamped {OUT.name} (names {named} of {locked} locked crates)")
    elif not m or m.group(1) != inputs_hash():
        sys.exit(f"FAIL: {OUT.name} is stale (Cargo.lock, a manifest, desktop/vendor or the cargo-about setup changed): "
                 "run scripts/rs.sh licenses and commit it")
    else:
        named, locked = check_content(text)
        print(f"ok  {OUT.name} is current and names {named} of {locked} locked crates")

main()
